export const personalInfo = {
  name: "ANKIT KUMAR MISHRA",
  title: "Full Stack Developer and Machine Learning Enthusiast",
  shortDescription:
    "Passionate about creating innovative solutions with modern technologies",
  description:
    "Motivated Full Stack Developer with experience in React, Next.js, Flask, FastAPI, and programming languages like Python, C, C++, and Java. Proficient in MySQL and MongoDB, with a strong foundation in OOPS, DBMS, and Data Structures.",
  email: "ankit.kumar.mishra2006@gmail.com",
  location: "Delhi, India",
  linkedin: "https://www.linkedin.com/in/ankit-kumar-mishra-0509982a5/",
  github: "https://github.com/ankitmishra2006",
  codolio: "https://codolio.com/profile/ankitmishra",
  resume:
    "https://drive.google.com/file/d/1TSxOEjhkFi8-_X1bVVHnYZMZAq9NKpnd/view?usp=sharing",
};

export const emailConfig = {
  apiUrl: "https://mail-sender-snowy.vercel.app/api/send-email",
  recipientEmail: "ankit.kumar.mishra2006@gmail.com",
};

export const skills = [
  { name: "JavaScript", color: "#F7DF1E", category: "Programming" },
  { name: "TypeScript", color: "#3178C6", category: "Programming" },
  { name: "C", color: "#A8B9CC", category: "Programming" },
  { name: "C++", color: "#00599C", category: "Programming" },
  { name: "Python", color: "#3776AB", category: "Programming" },
  { name: "SQL", color: "#336791", category: "Programming" },
  { name: "Java", color: "#ED8B00", category: "Programming" },
  { name: "Shell Scripting", color: "#89E051", category: "Programming" },

  { name: "Next.js", color: "#FFFFFF", category: "Frontend" },
  { name: "React", color: "#61DAFB", category: "Frontend" },
  { name: "React Native", color: "#61DAFB", category: "Frontend" },
  { name: "Expo", color: "#ED8B00", category: "Frontend" },
  { name: "GSAP", color: "#88CE02", category: "Frontend" },

  { name: "Node.js", color: "#339933", category: "Backend" },
  { name: "Flask", color: "#E74C3C", category: "Backend" },
  { name: "Socket.io", color: "#88CE02", category: "Backend" },
  { name: "WebRTC", color: "#333333", category: "Backend" },

  { name: "MongoDB", color: "#47A248", category: "Database" },
  { name: "MySQL", color: "#4479A1", category: "Database" },
  { name: "Oracle SQL", color: "#F80000", category: "Database" },
  { name: "PL/SQL", color: "#F80000", category: "Database" },
  { name: "SQLite", color: "#47A248", category: "Database" },

  { name: "NumPy", color: "#4479A1", category: "Machine Learning" },
  { name: "Pandas", color: "#FFB400", category: "Machine Learning" },
  { name: "Matplotlib", color: "#FCC624", category: "Machine Learning" },
  { name: "Seaborn", color: "#339933", category: "Machine Learning" },

  { name: "Git", color: "#F05032", category: "Tools" },
  { name: "Postman", color: "#FF6C37", category: "Tools" },
  { name: "Linux", color: "#FCC624", category: "Tools" },

  {
    name: "Object-Oriented Programming",
    color: "#FFB400",
    category: "Software Development",
  },

  { name: "DBMS", color: "#5B2C6F", category: "Software Development" },
  {
    name: "Operating Systems",
    color: "#2E86C1",
    category: "Software Development",
  },
  {
    name: "Computer Networks",
    color: "#16A085",
    category: "Software Development",
  },

  { name: "Scikit-Learn", color: "#F7931E", category: "Currently Learning" },
  { name: "Docker", color: "#FCC624", category: "Currently Learning" },
  { name: "Kubernetes", color: "#326CE5", category: "Currently Learning" },
  {
    name: "Data Structures & Algorithms",
    color: "#FF5733",
    category: "Currently Learning",
  },
];

export const projects = [
  {
    id: 1,
    name: "WanderLust",
    description:
      "A comprehensive full-stack travel accommodation web application inspired by Airbnb that enables users to explore, create, review, and manage property listings from around the world with interactive maps, secure authentication, and advanced search capabilities.",
    longDescription:
      "WanderLust is an enterprise-grade travel accommodation platform that combines modern web technologies with robust security features and intuitive design. The application provides secure user authentication using Passport.js with MongoDB session storage, comprehensive rate limiting, and CSRF protection. Property owners can create and manage listings with cloud-based image uploads via Cloudinary, while travelers can browse through an advanced search system with full-text indexing, interactive maps powered by MapTiler API, and a comprehensive review system with star ratings. Built with MVC architecture using Express.js and MongoDB, it features pagination for optimal performance, input validation with Joi schemas, and enterprise-level security including Helmet.js integration, MongoDB injection protection, and Content Security Policy implementation.",
    tech: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "EJS Templating",
      "Bootstrap 5",
      "Passport.js",
      "Cloudinary",
      "MapTiler API",
      "Joi Validation",
      "Helmet.js",
      "Express Rate Limit",
      "Express Mongo Sanitize",
      "Connect Flash",
      "Method Override",
      "Multer",
      "Connect Mongo",
      "Font Awesome",
    ],
    features: [
      "Secure user authentication with Passport.js and session management",
      "Property listing CRUD operations with image upload via Cloudinary",
      "Interactive map integration with automatic geocoding and coordinate storage",
      "Advanced search functionality with full-text indexing and pagination",
      "Comprehensive review and rating system (1-5 stars) with ownership protection",
      "Enterprise-level security with Helmet.js, rate limiting, and input sanitization",
      "Responsive design with Bootstrap 5 optimized for all devices",
      "Real-time flash messaging system and comprehensive error handling",
      "Protected routes with authorization and ownership validation",
      "Database indexing for optimized search performance and geographic queries",
      "Tax information toggle for transparent pricing display",
      "Cascade review deletion when listings are removed",
    ],
    color: "#4CAF50",
    gradient: "from-green-400 to-green-600",
    demoUrl: "https://wander-lust-mocha.vercel.app/listings",
    githubUrl: "https://github.com/AnkitMishra2006/WanderLust",
    status: "Completed",
  },
  {
    id: 2,
    name: "StreamiFy",
    description:
      "A modern language learning social platform that connects language learners worldwide through real-time chat and video calls, built with the MERN stack and powered by Stream.io to create meaningful connections between native speakers and language learners.",
    longDescription:
      "StreamiFy is a comprehensive language exchange platform that revolutionizes how people learn languages through social interaction. Built with React 19, Node.js, and MongoDB, it features intelligent language matching algorithms that connect native speakers with learners based on complementary language skills. The platform integrates Stream.io's chat and video infrastructure to provide seamless real-time communication, while offering a rich user experience with 20+ customizable themes, smart friend recommendations, and comprehensive profile management. With JWT-based authentication, HTTP-only cookies for security, and responsive design optimized for both desktop and mobile, StreamiFy creates an engaging environment for language practice and cultural exchange.",
    tech: [
      "React 19",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Stream.io",
      "Vite",
      "Tailwind CSS",
      "DaisyUI",
      "TanStack Query",
      "Zustand",
      "JWT",
      "Mongoose",
    ],
    features: [
      "Smart language partner matching based on native/learning language compatibility",
      "Real-time chat messaging powered by Stream Chat with rich features",
      "HD video calling integration using Stream Video SDK",
      "Comprehensive friend request system with accept/decline functionality",
      "JWT-based secure authentication with HTTP-only cookies",
      "Complete user onboarding with language preferences and profile setup",
      "20+ beautiful themes including light, dark, cupcake, and forest modes",
      "Auto-generated profile pictures for quick setup",
      "Real-time notifications for friend requests and messages",
      "Responsive design optimized for desktop and mobile devices",
      "Language flags and visual indicators for better UX",
      "Direct video call initiation from chat conversations",
    ],
    color: "#10B981",
    gradient: "from-emerald-500 to-green-600",
    demoUrl: "https://streamify-6ke5.onrender.com/",
    githubUrl: "https://github.com/AnkitMishra2006/StreamiFy",
    status: "Completed",
  },
  {
    id: 3,
    name: "Converso",
    description:
      "A voice-powered AI teaching platform that creates personalized learning experiences through conversational companions with real-time voice interaction and comprehensive session management.",
    longDescription:
      "Converso is a cutting-edge AI-powered educational platform that enables users to create custom AI teaching companions tailored to specific subjects and learning styles. Built with Next.js, TypeScript, and modern web technologies, it offers real-time voice interaction via VAPI, secure authentication through Clerk, and comprehensive learning analytics. Users can create companions for various subjects including Mathematics, Science, Language, History, Coding, and Economics, with customizable voice types, teaching styles, and session durations. The platform features session bookmarking, progress tracking, search and filtering capabilities, and a responsive design optimized for all devices. Perfect for students, educators, and learners seeking personalized AI-powered educational experiences.",
    tech: [
      "Next.js",
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Supabase",
      "Clerk",
      "VAPI",
      "Sentry",
      "Radix UI",
      "React Hook Form",
      "Zod",
      "Lottie React",
    ],
    features: [
      "Voice-enabled AI teaching companions with real-time interaction",
      "Custom companion creation with subject, topic, voice, and style selection",
      "Live transcription and conversation history",
      "Bookmark and session management system",
      "User authentication and role-based access control with Clerk",
      "Search and subject filtering capabilities",
      "Personal dashboard with learning analytics and progress tracking",
      "Responsive design optimized for desktop, tablet, and mobile",
      "Real-time error monitoring and performance tracking with Sentry",
      "Supabase database with Row Level Security policies",
      "Voice interaction powered by VAPI with speech-to-text and text-to-speech",
      "Session history and bookmarked companions management",
    ],
    color: "#fe5933",
    gradient: "from-orange-400 to-red-500",
    demoUrl: "https://converso-six.vercel.app/",
    githubUrl: "https://github.com/AnkitMishra2006/Converso",
    status: "Completed",
  },
  {
    id: 4,
    name: "Sonic Ring Run",
    description:
      "A fast-paced endless runner game featuring Sonic the Hedgehog, built with JavaScript and the Kaplay game engine. Features dynamic gameplay mechanics, progressive difficulty scaling, and immersive sound effects for an engaging browser-based gaming experience.",
    longDescription:
      "Sonic Ring Run is a modern endless runner game that brings the classic Sonic experience to the web browser. Built entirely with JavaScript and the Kaplay game engine, it features sophisticated sprite animations, precise collision detection, and a dynamic scoring system with multipliers. The game includes responsive controls supporting keyboard, mouse, and touch inputs, making it accessible across all devices. With carefully crafted game physics including gravity simulation and jump mechanics, progressive difficulty scaling, and a comprehensive ranking system from F to S grades, it delivers a console-quality gaming experience with smooth 60fps gameplay and immersive audio design.",
    tech: [
      "Kaplay",
      "JavaScript",
      "Vite",
      "2D Game Development",
      "Web Audio API",
    ],
    features: [
      "Endless side-scrolling gameplay with increasing difficulty",
      "Precise collision detection and sprite-based animations",
      "Dynamic scoring system with multiplier chains",
      "Responsive controls for keyboard, mouse, and touch",
      "Progressive difficulty scaling and speed increases",
      "Persistent high-score tracking with ranking system",
      "Immersive sound effects and background music",
      "Cross-platform browser compatibility",
    ],
    color: "#0066FF",
    gradient: "from-blue-500 to-blue-700",
    demoUrl: "https://sonic-runner06.netlify.app/",
    githubUrl: "https://github.com/AnkitMishra2006/Sonic-Runner",
    status: "Completed",
  },
  {
    id: 5,
    name: "Resumind",
    description:
      "An AI-powered resume analyzer that evaluates PDF resumes based on ATS compatibility and key hiring criteria, providing instant feedback and improvement tips to job seekers.",
    longDescription:
      "Resumind is a cutting-edge web application that revolutionizes the way job seekers optimize their resumes. Powered by advanced AI technology, it provides comprehensive analysis across multiple dimensions including ATS compatibility, content quality, structure optimization, and skills assessment. The application features drag & drop PDF upload, real-time AI analysis, beautiful score visualizations with animated gauges, and actionable improvement suggestions. Built with React 19, TypeScript, and Tailwind CSS, it offers a modern, responsive interface with secure authentication and file handling through Puter.js. Users can track their progress with detailed scoring across categories like Tone & Style, Content, Structure, and Skills, making it an essential tool for crafting job-winning resumes.",
    tech: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Vite",
      "Puter.js",
      "React Router",
      "PDF.js",
      "Zustand",
    ],
    features: [
      "AI-powered resume analysis with instant feedback",
      "ATS score visualization with animated gauges",
      "Multi-category scoring (Tone, Content, Structure, Skills)",
      "Drag & drop PDF upload with preview",
      "Secure authentication and cloud storage via Puter.js",
      "Responsive design with modern UI/UX",
      "Personal dashboard to track multiple resumes",
      "PDF to image conversion for easy viewing",
      "Real-time analysis status updates",
      "Actionable improvement suggestions",
      "Enterprise-grade security and privacy",
      "Fast performance with Vite optimization",
    ],
    color: "#6366F1",
    gradient: "from-indigo-400 to-indigo-600",
    demoUrl: "https://resumind-resume-analyzer.vercel.app/",
    githubUrl: "https://github.com/AnkitMishra2006/ai-resume-analyzer",
    status: "Completed",
  },
  {
    id: 6,
    name: "Talkative",
    description:
      "A modern, full-stack real-time chat application built with React, Node.js, Socket.IO, and MongoDB that enables users to communicate instantly with secure authentication, file sharing, and online status tracking.",
    longDescription:
      "Talkative is a comprehensive real-time messaging platform that combines cutting-edge web technologies with an intuitive user experience. The application features secure JWT-based authentication with bcrypt password hashing, real-time bidirectional communication through Socket.IO, and persistent message storage in MongoDB. Users can share images via Cloudinary integration, track online status in real-time, manage their profiles, and enjoy a responsive design built with Tailwind CSS and DaisyUI. The application follows modern development practices with a clean separation between frontend and backend, state management through Zustand, and supports multiple themes for personalization.",
    tech: [
      "React 18",
      "Node.js",
      "Express.js",
      "Socket.IO",
      "MongoDB",
      "Mongoose",
      "JWT",
      "bcryptjs",
      "Vite",
      "Tailwind CSS",
      "DaisyUI",
      "Zustand",
      "Cloudinary",
      "Axios",
      "React Router",
    ],
    features: [
      "Real-time messaging with instant delivery using Socket.IO",
      "Secure JWT-based authentication with password hashing",
      "Image sharing and file upload with Cloudinary integration",
      "Live online status tracking for all users",
      "Profile management with avatar updates",
      "Responsive design optimized for desktop and mobile",
      "Multiple theme support for UI personalization",
      "Persistent message history stored in MongoDB",
      "Modern UI built with Tailwind CSS and DaisyUI components",
      "Real-time toast notifications for user feedback",
    ],
    color: "#00D9FF",
    gradient: "from-cyan-400 to-blue-500",
    demoUrl: "https://talkative-udcm.onrender.com/",
    githubUrl: "https://github.com/AnkitMishra2006/talkative",
    status: "Completed",
  },
  {
    id: 7,
    name: "AI News Summarizer Extension",
    description:
      "A powerful Chrome extension that intelligently extracts and summarizes article content from any webpage using Google's Gemini AI, providing instant customizable summaries without leaving your browser.",
    longDescription:
      "This Chrome extension revolutionizes how users consume online content by providing instant, AI-powered article summarization using Google Gemini 1.5 Flash. The extension features smart text extraction that automatically detects article content, offers three distinct summary types (brief, detailed, and bullet points), and includes a clean popup interface with one-click copy functionality. Built with Chrome Extension Manifest V3, it securely stores API keys using Chrome's sync storage and works across all websites with proper article structure.",
    tech: [
      "JavaScript",
      "Chrome Extension APIs",
      "Google Gemini AI",
      "Manifest V3",
    ],
    features: [
      "Smart text extraction from any webpage",
      "Three AI-powered summary modes (brief, detailed, bullet points)",
      "Google Gemini 1.5 Flash integration",
      "One-click copy to clipboard functionality",
      "Secure API key storage with Chrome sync",
      "Clean, responsive popup interface",
      "Universal website compatibility",
      "Real-time AI processing with loading indicators",
    ],
    color: "#4285F4",
    gradient: "from-blue-500 to-indigo-600",
    demoUrl:
      "https://drive.google.com/file/d/1y1uShnFD_tyRpvQx387UNsI2Z4ZkH-Uc/view?usp=sharing",
    githubUrl: "https://github.com/AnkitMishra2006/Article-Summarizer",
    status: "Completed",
  },
  {
    id: 8,
    name: "WhisprNote - Anonymous Feedback Web App",
    description:
      "A modern full-stack anonymous messaging platform with email verification, AI-powered suggestions, and customizable privacy settings — built with Next.js 15 for secure, private communication.",
    longDescription:
      "WhisprNote is a comprehensive web application that enables users to receive honest, anonymous feedback through unique shareable links. Built with Next.js 15 and the App Router, it features a robust authentication system with email verification using Resend API and secure OTP verification. Users get a personalized URL (/u/username) where anyone can send anonymous messages without creating an account. The platform integrates HuggingFace's Mistral-7B model to provide AI-generated conversation starters, helping senders craft meaningful messages. Users have complete control over their privacy with toggleable message acceptance settings. The application features a clean, responsive design built with Tailwind CSS v4 and ShadCN UI components, making it perfect for content creators, professionals, students, and anyone seeking genuine feedback from their network.",
    tech: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS v4",
      "MongoDB",
      "NextAuth v4",
      "Resend API",
      "HuggingFace AI",
      "ShadCN UI",
      "Zod Validation",
    ],
    features: [
      "Email verification with secure OTP system using Resend API",
      "Anonymous message sending via unique shareable user links",
      "AI-powered conversation starters using HuggingFace Mistral-7B",
      "Toggle privacy controls to enable/disable message acceptance",
      "Secure authentication with NextAuth v4 and JWT sessions",
      "Real-time dashboard for message management and deletion",
      "Responsive design optimized for all devices",
      "Beautiful email templates with React Email components",
      "Username uniqueness validation and secure password hashing",
      "Modern UI with ShadCN components and Lucide React icons",
      "Form validation with React Hook Form and Zod schemas",
      "Interactive message carousel showcasing platform features",
    ],
    color: "#3B82F6",
    gradient: "from-blue-500 to-purple-600",
    demoUrl: "https://whispr-note.vercel.app",
    githubUrl: "https://github.com/AnkitMishra2006/Whispr-Note",
    status: "Completed",
  },
  {
    id: 9,
    name: "React Movie App",
    description:
      "A modern, responsive movie discovery application built with React, Vite, and TailwindCSS. Search through thousands of movies, discover trending films, and get detailed information about your favorite movies using The Movie Database (TMDb) API.",
    longDescription:
      "React Movie App is a comprehensive movie discovery platform that leverages The Movie Database (TMDb) API to provide users with access to thousands of movies. The application implements advanced search functionality with debounced input using react-use to optimize API calls and reduce server load. User search patterns are intelligently tracked using Appwrite database - when users search for movies, the system either increments existing search counts or creates new entries. This data powers a dynamic trending section that showcases the top 5 most searched movies based on real user interactions. The app features a modern, responsive design built with TailwindCSS 4.0, includes comprehensive movie details like ratings, release years, and original languages, and provides fallback images for missing posters. Built with React 19.0 and Vite 6.2 for lightning-fast performance and development experience.",
    tech: ["React", "Vite", "TailwindCSS", "Appwrite", "TMDb API", "React-Use"],
    features: [
      "Real-time movie search with debounced input for optimal performance",
      "Trending movies dashboard showing top 5 most searched films",
      "Comprehensive movie details including ratings, release year, and language",
      "Fully responsive design optimized for desktop, tablet, and mobile",
      "Lightning-fast performance with Vite hot module replacement",
      "Search analytics and pattern tracking using Appwrite database",
      "Smart loading states with user-friendly spinners",
      "Fallback images for graceful handling of missing movie posters",
      "Modern UI/UX with gradient effects and smooth animations",
      "Environment-based configuration for API keys and database credentials",
      "Error handling with user-friendly messages",
      "Efficient API calls with 500ms debounce to reduce server load",
    ],
    color: "#06B6D4",
    gradient: "from-cyan-400 to-cyan-600",
    demoUrl:
      "https://react-movie-6m1vqkdwj-ankitmishra2006s-projects.vercel.app/",
    githubUrl: "https://github.com/AnkitMishra2006/React-Movie-App",
    status: "Completed",
  },
  {
    id: 10,
    name: "Music Academy Website",
    description:
      "A modern, responsive web application for a fictional Music Academy built with Next.js 15, TypeScript, and Tailwind CSS, featuring advanced UI components and smooth animations.",
    longDescription:
      "Music Academy is a fully responsive web application created to showcase modern web development techniques using Next.js 15 and advanced UI components. The project features a comprehensive music academy website with interactive 3D cards, animated backgrounds, testimonial carousels, and instructor showcases. Built with TypeScript for type safety and Tailwind CSS for styling, it includes custom UI components like background beams, wavy backgrounds, infinite moving cards, and sticky scroll reveals. The site demonstrates advanced animation techniques using Framer Motion and includes course management, webinar listings, contact forms, and a complete responsive design system optimized for all devices.",
    tech: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
    ],
    features: [
      "Interactive 3D card effects with depth and hover animations",
      "Advanced background animations (beams, waves, gradients, spotlight)",
      "Responsive design optimized for desktop, tablet, and mobile",
      "Dynamic course management with JSON-based data",
      "Infinite scrolling testimonial carousel",
      "Animated instructor showcase with tooltips",
      "Sticky scroll reveal for progressive content unveiling",
      "Contact form with background beam effects",
      "Server-side rendering with Next.js App Router",
      "TypeScript integration for complete type safety",
      "Custom utility functions for className management",
      "Performance optimized with image optimization and lazy loading",
    ],
    color: "#06B6D4",
    gradient: "from-cyan-500 to-teal-600",
    demoUrl: "https://music-academy-lyart.vercel.app/",
    githubUrl: "https://github.com/AnkitMishra2006/Music-Academy",
    status: "Completed",
  },
  {
    id: 11,
    name: "Mojito Cocktails - Velvet Pour",
    description:
      "A fully animated, scroll-responsive UI for a fictional cocktail bar built using GSAP, React, and Tailwind CSS to practice creative frontend animations.",
    longDescription:
      "Mojito Cocktails is a frontend-only project designed to explore advanced GSAP animation capabilities in a realistic, themed setting. It features scroll-triggered animations, a full-screen hero with animated text, a scroll-pinned background video, and a cocktail slider with masked image effects. The layout adapts responsively across screen sizes, using react-responsive for breakpoint handling. With dynamic transitions, parallax movement, and timeline-based sequences, this project acts as a playground for exploring visual storytelling in web development.",
    tech: ["React", "GSAP", "Tailwind CSS"],
    features: [
      "Scroll-triggered text and image animations using GSAP",
      "SplitText typography animations for headers",
      "Scroll-pinned background video synced to scroll progress",
      "Cocktail slider with tab navigation and dynamic transitions",
      "Fully responsive layout with media queries via react-responsive",
      "Custom masked image effects using CSS and GSAP",
      "Layered noise textures and modern gradients",
      "Multi-section layout including Hero, About, Art, Menu, and Contact",
    ],
    color: "#e7d393",
    gradient: "from-yellow-400 to-yellow-600",
    demoUrl: "https://mojito-cocktails-zeta.vercel.app/",
    githubUrl: "https://github.com/AnkitMishra2006/mojito-cocktails",
    status: "Completed",
  },
  {
    id: 12,
    name: "Shaurya Shandilya Portfolio",
    description:
      "A professional and visually rich portfolio for a law student, crafted using Next.js, Tailwind CSS, and Shadcn UI, highlighting legal internships, education, and contact integration.",
    longDescription:
      "Shaurya Shandilya's portfolio is a fully responsive personal website designed for a BA LLB student to showcase their academic background, legal experience, and professional profile. Built with Next.js 15, React 19, TypeScript, and Tailwind CSS with Radix UI components, the project features animated sections including Hero, About, Skills, Projects, Education, and Contact. It includes a functional contact form with email handling, theme switching capabilities, and smooth scroll navigation. The site uses a sophisticated color palette of navy, gold, and taupe with custom animations and hover effects. The portfolio showcases legal internships at Kumar Chandiwal Associates, The Amikus Qriae, and Legal Vidhiya, along with community service experience. It serves as a polished digital identity for aspiring legal professionals with resume download functionality and professional branding.",
    tech: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Radix UI",
      "React Hook Form",
      "Zod",
      "Lucide React",
    ],
    features: [
      "Hero section with animated profile photo, introduction, and Google Drive resume download",
      "Interactive About section with philosophy cards and legal expertise badges",
      "Education timeline showcasing BA LLB program with subject highlights and institution details",
      "Skills section with categorized legal and technical competencies using color-coded cards",
      "Projects gallery featuring legal internships and volunteer work with detailed descriptions",
      "Contact form with React Hook Form validation and Zod schema validation",
      "Dark/light mode theme switching using next-themes",
      "Fully responsive design with mobile-first approach using Tailwind CSS",
      "Smooth scroll navigation and fade-in animations with custom CSS utilities",
      "Toast notifications for user feedback using Sonner",
      "Professional color scheme with navy, gold, and taupe palette",
      "Accessible components built with Radix UI primitives",
    ],
    color: "#1A2633",
    gradient: "from-taupe to-white-custom",
    demoUrl: "https://shaurya-portfolio-phi.vercel.app/",
    githubUrl: "https://github.com/AnkitMishra2006/Shaurya-Portfolio",
    status: "Completed",
  },
  {
    id: 13,
    name: "Nike UI Clone",
    description:
      "A modern, responsive UI clone of Nike's landing page built using React, Tailwind CSS, and Vite to practice pixel-perfect layouts and interactive components.",
    longDescription:
      "Nike UI Clone is a frontend-only project that recreates the sleek and bold aesthetic of Nike's product landing pages. Built with React 19 and Tailwind CSS, the project showcases a hero section with interactive shoe selector and dynamic image switching, product highlights with responsive grid layouts, promotional sections, customer reviews, and newsletter subscription. The design emphasizes responsiveness, component reusability, and modern UI styling with utility-first CSS. Features include dynamic state management for shoe selection, responsive design across all devices, custom utility classes, and clean component architecture. The layout adapts smoothly across devices while maintaining Nike's design language and brand aesthetics.",
    tech: ["React", "Tailwind CSS", "Vite"],
    features: [
      "Fully responsive landing page layout with mobile-first approach",
      "Interactive hero section with dynamic shoe image switching",
      "Product grid with responsive cards and consistent styling",
      "Reusable UI components (Button, Cards, Navigation) for scalability",
      "Custom Tailwind CSS utility classes and design system",
      "React hooks for state management and interactive features",
      "Mobile-friendly hamburger navigation menu",
      "Statistics display with engaging number presentations",
      "Customer review testimonials with rating system",
      "Newsletter subscription form with modern input design",
      "Services section with icon-based feature cards",
      "Footer with social media links and organized navigation",
      "Clean, maintainable React component architecture",
      "Custom color palette matching Nike's brand identity",
      "Typography system with Google Fonts integration",
    ],
    color: "#FF6452", // Nike's coral-red color from the project
    gradient: "from-red-500 to-red-600",
    demoUrl: "https://nike-clone-ankit.vercel.app/", // update if deployed
    githubUrl: "https://github.com/AnkitMishra2006/Nike-UI", // update if needed
    status: "Completed",
  },
  {
    id: 14,
    name: "Smart Notes",
    description:
      "An intelligent AI-powered note-taking application that combines seamless note management with advanced AI chat functionality, enabling users to ask questions about their notes and get intelligent responses using vector embeddings and RAG (Retrieval Augmented Generation) technology.",
    longDescription:
      "Smart Notes is a cutting-edge note-taking platform that revolutionizes how users interact with their personal knowledge base. Built with Next.js 15 and powered by Convex for real-time backend operations, the application features sophisticated AI integration using free APIs including Groq for language model processing and Hugging Face for vector embeddings. Users can create, manage, and search through their notes while leveraging an intelligent AI chatbot that understands context and provides relevant responses based on note content. The platform includes secure authentication, real-time synchronization, markdown support, and a modern responsive interface with dark mode functionality.",
    tech: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Convex",
      "Tailwind CSS",
      "shadcn/ui",
      "Vercel AI SDK",
      "Groq API",
      "Hugging Face API",
      "Convex Auth",
      "React Hook Form",
      "Zod Validation",
      "Lucide React",
      "next-themes",
    ],
    features: [
      "AI-powered chat interface with natural language processing",
      "Vector embeddings for semantic search and content retrieval",
      "Real-time note synchronization across all devices",
      "Secure user authentication and session management",
      "Markdown support for rich text formatting",
      "RAG (Retrieval Augmented Generation) for contextual responses",
      "Responsive design with dark/light mode toggle",
      "Free API integration (Groq + Hugging Face)",
      "Real-time streaming AI responses",
      "Comprehensive note management (CRUD operations)",
      "Modern UI with shadcn/ui components",
      "TypeScript for enhanced developer experience",
    ],
    color: "#6366F1",
    gradient: "from-indigo-400 to-purple-600",
    demoUrl: "https://smart-notes-ai.vercel.app",
    githubUrl: "https://github.com/AnkitMishra2006/AI-Notes-App",
    status: "In Progress",
  },
];

export const experiences = [
  {
    id: 1,
    title: "B.Tech in Computer Science Engineering",
    company: "Maharaja Surajmal Institute of Technology",
    period: "Aug '23 — Present",
    description:
      "Currently pursuing Bachelor's degree with CGPA: 8.265. Focusing on advanced programming concepts, data structures, algorithms, software engineering principles, and emerging technologies like AI/ML.",
    type: "education",
    skills: [
      "Data Structures & Algorithms",
      "Object-Oriented Programming",
      "Software Engineering",
      "Database Management",
      "Operating Systems",
      "Computer Networks",
      "AI/ML",
    ],
    achievements: [
      "Maintained 8.265 CGPA",
      "Completed 15+ technical projects",
      "Active in coding competitions",
    ],
  },

  {
    id: 2,
    title: "Web Developer Member",
    company: "Microsoft Students Chapter (MSC) Club",
    period: "Sep '24 — Sep '25",
    description:
      "Collaborated on maintaining and enhancing the MSC website by implementing new features for events and initiatives. Developed a browser-based game for an internal competition, showcasing creativity, technical expertise, and problem-solving skills.",
    type: "organization",
    skills: [
      "Web Development",
      "JavaScript",
      "Frontend Design",
      "Problem Solving",
    ],
    achievements: [
      "Implemented new website features for society events",
      "Maintained and optimized MSC's web platform",
      "Created a browser-based game for an internal competition",
    ],
  },

  {
    id: 3,
    title: "Data Analyst",
    company: "V Devi Foundation",
    period: "May '25",
    description:
      "Collected, cleaned, and organized large datasets from multiple sources, ensuring data accuracy and integrity. Performed statistical analysis and developed visual reports using Excel and Python (pandas, NumPy) to present actionable insights to stakeholders.",
    type: "work",
    skills: [
      "Data Analysis",
      "Python",
      "Excel",
      "Data Cleaning",
      "Statistical Analysis",
      "Data Visualization",
    ],
    achievements: [
      "Streamlined data cleaning processes, reducing errors by 25%",
      "Created automated Excel and Python-based reporting workflows",
      "Delivered actionable insights leading to improved decision-making",
    ],
  },

  {
    id: 4,
    title: "Full Stack Web Developer Intern",
    company: "Gera & Associates",
    period: "Jun '25 — Aug '25",
    description:
      "Built a portfolio website for a construction firm using Flask, HTML, CSS, and JavaScript. Developed two microservices: a Mail Sender API for contact form handling and RoboSheets for Google Sheets integration. Implemented SEO optimization and responsive design.",
    type: "work",
    skills: [
      "Flask",
      "Node.js",
      "Express.js",
      "HTML5",
      "CSS3",
      "JavaScript",
      "Bootstrap 5",
      "Google Sheets API",
      "SEO",
      "Vercel",
    ],
    achievements: [
      "Built full-stack portfolio website for 500+ construction projects",
      "Developed and deployed Mail Sender API microservice on Vercel",
      "Created RoboSheets service for real-time Google Sheets integration",
      "Implemented comprehensive SEO optimization with sitemaps and schema markup",
      "Designed responsive UI/UX with Bootstrap 5 and mobile-first approach",
    ],
  },
];

export const navItems = [
  { name: "Home", href: "#home" },
  { name: "Skills", href: "#skills" },
  { name: "Projects", href: "#projects" },
  { name: "Experience", href: "#experience" },
  { name: "Contact", href: "#contact" },
];
